export const LOAD_RECIPES="LOAD_RECIPES"
export const GET_RECIPES_SUCCESS="GET_RECIPES_SUCCESS"
export const GET_RECIPES_FAIL="GET_RECIPES_FAIL"

export const LOAD_RECIPE="LOAD_RECIPE"
export const GET_RECIPE_SUCCESS="GET_RECIPE_SUCCESS"
export const GET_RECIPE_FAIL="GET_RECIPE_FAIL"